name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.3'
        check-latest: true
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v -p=1 ./...
